sudo: false
dist: groovy

  - cd ~
  - sudo apt-get install cppcheck ggcov lcov valgrind kcachegrind

# Enable C++ support
language: cpp
script:
  - git clone https://github.com/behnamasadi/cmake_tutorials/
  - cd cmake_tutorials
  - mkdir build
  - cd build
  - cmake .. && make -j8
  - ctest  tests
